base_url = "https://example.github.io/blog"

title       = "shanshan's blog"
description = "tech & life"

compile_sass   = true
minify_html    = false
generate_feeds = false

taxonomies = [
    { name = "tags" },
]

[markdown.highlighting]
theme = "github-light"
