base_url = "https://tsukiyokai.github.io"

title            = "shanshan's blog"
description      = "tech & life"
default_language = "zh"

compile_sass   = true
minify_html    = false
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
    { name = "tags" },
]

[markdown]
smart_punctuation              = true
external_links_target_blank    = true

[markdown.highlighting]
theme = "github-light"
