
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/stackoverflow-dark.min.css
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/zenburn.min.css
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/school-book.min.css
#- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/gradient-light.min.css
- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/an-old-hope.min.css
- https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Ma+Shan+Zheng&family=Noto+Serif+SC:wght@600&display=swap

# scripts loaded in the end of the body
scripts_defer:
#- https://cdn.bootcdn.net/ajax/libs/highlight.js/11.0.0-alpha0/highlight.min.js # for highlight
- https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
- /js/paper.js # for basic script


social:
  Github: https://github.com/tsukiyokai
  E-mail: mailto:tsukiyokai@hotmail.com
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
#toc: false
#link: false
#archives: false
#categories: false
#tags: false

# theme color
main_color: forest # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: xx-xxxxxxx-xx

# commend module
comment:
  enable: false
  appId: your-app-id
  appKey: your-app-key
  placeholder: say something
  notify: false
  verify: false
  avatar: mp
